# Generated by Django 4.2 on 2023-04-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_income2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income2',
        ),
    ]
